// Mocks generated by Mockito 5.4.4 from annotations
// in beta_app/test/mocks/mock_data_management_provider.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i10;

import 'package:beta_app/modules/data_management/models/database_data_file.dart'
    as _i6;
import 'package:beta_app/modules/data_management/providers/data_management_provider.dart'
    as _i5;
import 'package:beta_app/modules/database/models/data_record.dart' as _i9;
import 'package:beta_app/modules/database/providers/i_database_provider.dart'
    as _i4;
import 'package:beta_app/modules/input_output/services/i_file_service.dart'
    as _i3;
import 'package:beta_app/modules/logging/providers/i_logging_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeILoggingProvider_0 extends _i1.SmartFake
    implements _i2.ILoggingProvider {
  _FakeILoggingProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIFileService_1 extends _i1.SmartFake implements _i3.IFileService {
  _FakeIFileService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIDatabaseProvider_2 extends _i1.SmartFake
    implements _i4.IDatabaseProvider {
  _FakeIDatabaseProvider_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DataManagementProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataManagementProvider extends _i1.Mock
    implements _i5.DataManagementProvider {
  MockDataManagementProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ILoggingProvider get logger => (super.noSuchMethod(
        Invocation.getter(#logger),
        returnValue: _FakeILoggingProvider_0(
          this,
          Invocation.getter(#logger),
        ),
      ) as _i2.ILoggingProvider);

  @override
  _i3.IFileService get fileService => (super.noSuchMethod(
        Invocation.getter(#fileService),
        returnValue: _FakeIFileService_1(
          this,
          Invocation.getter(#fileService),
        ),
      ) as _i3.IFileService);

  @override
  _i4.IDatabaseProvider get databaseProvider => (super.noSuchMethod(
        Invocation.getter(#databaseProvider),
        returnValue: _FakeIDatabaseProvider_2(
          this,
          Invocation.getter(#databaseProvider),
        ),
      ) as _i4.IDatabaseProvider);

  @override
  List<_i6.DatabaseDataFile> get dataFiles => (super.noSuchMethod(
        Invocation.getter(#dataFiles),
        returnValue: <_i6.DatabaseDataFile>[],
      ) as List<_i6.DatabaseDataFile>);

  @override
  bool get showImagesOnly => (super.noSuchMethod(
        Invocation.getter(#showImagesOnly),
        returnValue: false,
      ) as bool);

  @override
  List<_i6.DatabaseDataFile> get filteredFiles => (super.noSuchMethod(
        Invocation.getter(#filteredFiles),
        returnValue: <_i6.DatabaseDataFile>[],
      ) as List<_i6.DatabaseDataFile>);

  @override
  List<String> get tableHeaders => (super.noSuchMethod(
        Invocation.getter(#tableHeaders),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<List<String>> get tableData => (super.noSuchMethod(
        Invocation.getter(#tableData),
        returnValue: <List<String>>[],
      ) as List<List<String>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialize({required String? sessionType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#sessionType: sessionType},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadDataFiles({required String? sessionType}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadDataFiles,
          [],
          {#sessionType: sessionType},
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> toggleShowImages() => (super.noSuchMethod(
        Invocation.method(
          #toggleShowImages,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> previewFile(String? filename) => (super.noSuchMethod(
        Invocation.method(
          #previewFile,
          [filename],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> addFile(
    _i6.DatabaseDataFile? file,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFile,
          [
            file,
            metadata,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteFile(String? filename) => (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [filename],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> updateFileMetadata(
    String? id,
    Map<String, dynamic>? metadata,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileMetadata,
          [
            id,
            metadata,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> shareFile(String? filename) => (super.noSuchMethod(
        Invocation.method(
          #shareFile,
          [filename],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void clearPreview() => super.noSuchMethod(
        Invocation.method(
          #clearPreview,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String generateFilename(String? serialNumber) => (super.noSuchMethod(
        Invocation.method(
          #generateFilename,
          [serialNumber],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #generateFilename,
            [serialNumber],
          ),
        ),
      ) as String);

  @override
  _i7.Future<void> saveRealTimeData(
    Map<String, dynamic>? data,
    String? sessionType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveRealTimeData,
          [
            data,
            sessionType,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> loadJsonDataFiles() => (super.noSuchMethod(
        Invocation.method(
          #loadJsonDataFiles,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  List<_i9.DataRecord> fetchGraphRecordsBySession(String? sessionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchGraphRecordsBySession,
          [sessionId],
        ),
        returnValue: <_i9.DataRecord>[],
      ) as List<_i9.DataRecord>);

  @override
  _i7.Future<void> markFileAsDeleted(String? fileName) => (super.noSuchMethod(
        Invocation.method(
          #markFileAsDeleted,
          [fileName],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
